### ISSUE TITLE
Not Able to receive payment prompt on my mobile

### ISSUE THREAD

**Issue by mauladmin** [iplusacademy/moodle-paygw_mtnafrica#1]
I switched to the live environment with the MTN Live keys, however, when I initiate a payment for the course on the e-Learning platform, I don't receive a prompt or message to pay on my mobile phone. I'm using a Ugandan code of 256785....... on my profile.

**Comment by iplusacademy** [comment]
Testing is done in a sandbox environment, unless you want to lose real money. The MTN keys should work in a live environment AND a sandbox environment.  The only difference is that the live environment works with actual money, the sandbox environment works with fake money.

**Comment by mauladmin** [comment]
But at least I should see a prompt asking me to input my MTN MoMo PIN to pay for the course but this doesn't show. I am also willing to pay for the course to see what comes next after paying. Ideally, I want to test the live environment with actual money.

**Comment by iplusacademy** [comment]
What do you see when you enable debugging in your browser (F12) in the console window?

Sample:
```
index.php:1 Uncaught (in promise) Exception - Server error: `POST https://sandbox.momodeveloper.mtn.com/collection/v1_0/requesttopay` resulted in a `500 Server Error` response:
{"message":"Currency not supported.","code":"INVALID_CURRENCY"}
```
or:
```
Starting Moodle session timeout warning.
first.js:4983 Enrolment in course Test course 1
first.js:4983 mtn Africa payment rejected
```
Also the Moodle logs can reveal information, search all logs that have 'MTN Africa' in the component columns.

**Comment by iplusacademy** [comment]
Can you  confirm that testing has to be done in a production environment?

If you confirm we should drop the test environment test.medical-access.org and work immediately in e-learning.medical-access.org.

**Comment by mauladmin** [comment]
> Can you confirm that testing has to be done in a production environment?
> 
> If you confirm we should drop the test environment test.medical-access.org and work immediately in e-learning.medical-access.org.

For the lack of a better word, I used test. But maybe let me put it this way. I need to pay for the course and get enrolled now that MTN is switched to Live.

**Comment by iplusacademy** [comment]
Moodle uses continuous integration, not a one time payment as a check that it works or not.

If you test with real money in a production environment (I think the minimal amount  is 5000 UGX), you should do the tests each month.  

Where are the logs of your tests? Where are the screenshots?

**Comment by iplusacademy** [comment]
MTN testing is done by telephone number. If you use the numbers provided by the MTN website you can see the results:

This is what the [MTN website](https://momodeveloper.mtn.com/api-documentation/testing/) says
46733123450	failed
46733123451	rejected
46733123452	timeout
46733123453	ongoing (will answer pending first and if requested again after 30 seconds it will respond success)
46733123454	pending
Any other Number results in Success

This is not correct, just try 46733123455 and you will see that you do not receive a Success message.

However when you use the number [46733123999](https://github.com/iplusacademy/moodle-paygw_mtnafrica/blob/main/tests/mtn_helper_test.php#L173C27-L173C38) you will receive a success message and enrolled in the course.

So to test you use the directions provided by MTN Africa. You will not be prompted to enter data on your userphone, but based on the number enterred on the profile page of your user, you will be enrolled or not.


How this works in a non sandbox environment, I do not know.  I asked in the very beginning how a payment process worked in Uganda. Peace explained all steps that have to be done. Perhaps she is the best person to help which MTN mobile app you have to install to see the payment promt.

**Comment by mauladmin** [comment]
I want engage MTN about this to find out why in the non sandbox environment it doesn't work. But before I reach out to MTN, please help me understand what should be entered under Client ID because all along I had filled it with the same key as the primary key and when I revisited the README file, it doesn't talk about the Client ID anywhere. It only mentions the primary and secondary keys. So I need to be sure that it's not the cause of my failure to receive the prompt on my phone.

**Comment by mauladmin** [comment]
> MTN testing is done by telephone number. If you use the numbers provided by the MTN website you can see the results:
> 
> This is what the [MTN website](https://momodeveloper.mtn.com/api-documentation/testing/) says 46733123450 failed 46733123451 rejected 46733123452 timeout 46733123453 ongoing (will answer pending first and if requested again after 30 seconds it will respond success) 46733123454 pending Any other Number results in Success
> 
> This is not correct, just try 46733123455 and you will see that you do not receive a Success message.
> 
> However when you use the number [46733123999](https://github.com/iplusacademy/moodle-paygw_mtnafrica/blob/main/tests/mtn_helper_test.php#L173C27-L173C38) you will receive a success message and enrolled in the course.
> 
> So to test you use the directions provided by MTN Africa. You will not be prompted to enter data on your userphone, but based on the number enterred on the profile page of your user, you will be enrolled or not.
> 
> How this works in a non sandbox environment, I do not know. I asked in the very beginning how a payment process worked in Uganda. Peace explained all steps that have to be done. Perhaps she is the best person to help which MTN mobile app you have to install to see the payment promt.

There is no special app needed. Peace used a **Jumia Application** which is integrated with the payment API to share the possible steps taken. There is no special application, it's direct integration between Jumia and MTN and Airtel

**Comment by mauladmin** [comment]
> I want engage MTN about this to find out why in the non sandbox environment it doesn't work. But before I reach out to MTN, please help me understand what should be entered under Client ID because all along I had filled it with the same key as the primary key and when I revisited the README file, it doesn't talk about the Client ID anywhere. It only mentions the primary and secondary keys. So I need to be sure that it's not the cause of my failure to receive the prompt on my phone.

Hello Renaat, any response for me on this?

**Comment by iplusacademy** [comment]
I asked, in a meeting where you were present, MTN clarification about the clientID - primary key - api key - subscription key -  ocp-apim key - ....  They gave no explanation at all, pretended is was crystal clear but sometimes use ocp-apim, sometimes api, sometimes subscription key.

**Comment by mauladmin** [comment]
> I asked, in a meeting where you were present, MTN clarification about the clientID - primary key - api key - subscription key - ocp-apim key - .... They gave no explanation at all, pretended is was crystal clear but sometimes use ocp-apim, sometimes api, sometimes subscription key.

Let me reach out to MTN for clarity.

**Comment by mauladmin** [comment]
I reached out to the MTN support team and got some clarification. The team indicated that to have a successful transaction we need the following 3 things listed below
**1.	The API User 
2.	The API Key 
3.	The Subscription key / Ocp-Apim-Subscription-Key.**

The **API User and API Key** are found on the Mobile Money Portal, and I have been able to generate them. Then the **Subscription key / Ocp-Apim-Subscription-Key** is the variable for the Primary and Secondary keys and they are available on the developer portal.

Now with this explanation, I would like to find out where to insert the API User and API Key details because the current fields on the platform show 3 fields i.e., Client ID, Primary key, and Secondary Key.

**Comment by iplusacademy** [comment]
So the subcription key is the primary key and the ocp-apim-subsription-key is the secondary key? Why do they once call it subscription key and once primary key?

Please reach out the MTN support team and add clarification when I have to use this API user and when API key. During the development of this plugin this data was not available, but I had to implement and even document it,  Now Maul is sending me only screenshots, where I do not see any help links nor can check if this API user is even linked to the secrets.

If MTN is making it complex, they will have to admid that adding an extra layer, will only complicate things, not simplifying.  When Maul is not providing access to the actual keys, I have to work blind.

**Comment by mauladmin** [comment]
I already reached out to the MTN support team and they explained as I indicated in an email like 2 weeks back. The subscription key is the same as the Ocp-Apim-Subscription-Key. Ocp-Apim-Subscription-Key is just a variable whose value is the subscription key and a subscription key either the primary or secondary key. I tested this in Postman, and it works whether you use the primary or secondary key for this entry. 

This information was there already. It is just that personally, I hadn't given a lot of time to digest it. But when I compare it with what I did in Postman like 4 months a go, these are the same parameters I used although I was not getting it directly from the documentation but the video tutorial I was following was using this developer documentation and the video is old. So the information was there but maybe you could have skipped it.

About MAUL sharing screenshots, It was your request that you needed screenshots, not links for you to get the keys for both the production and sandbox environment. I am going to share the links and credentials for you to log in and get the keys as you want. For the sandbox environment, I already shared them but I will re-share and you will use them to generate the API user and API key because as I indicated or how the documentation says that these keys are provisioned differently in the sandbox, and the production.

**Comment by ewallah** [comment]
Done
