### ISSUE TITLE
confusing security check?

### ISSUE THREAD

**Issue by danmarsden** [iplusacademy/moodle-paygw_mtnafrica#7]
on the Moodle security report I see an error added by this plugin:

Warning	HTTP Port should be open for sandbox testing

But the check doesn't actually seem to be doing anything - just printing some text?

If you have long term plans to make this actually do something you might want to comment out the check for now so it doesn't confuse people. (like it did me...) :-)

**Comment by iplusacademy** [comment]
The MTN API is [clear](https://momodeveloper.mtn.com/faqs#5NWBd) about the callback: they use https for a production environment and http for the sandbox environment.

From the very beginning, I contacted MTN to report a problem:  posting financial transaction ids, private telephone numbers, ... using http is a security problem. Their answer was simple: these unsecure posts are safe(sic) and they have no plans to change it in the future.  Hence the need for a warning, but also the design of this plugin (it can work with but also without the callback).

Perhaps a critical warning should be shown when the sandbox environment is enabled, and normal info when the sandbox is not enabled (an informed admin is a better admin)?

Anyhow I will try to rephrase the strings check_details and check_warning to explain better what's the problem.

**Comment by danmarsden** [comment]
I see what you mean - I'm not sure it quite makes sense as a security check though - I think I'd be more inclined to put something on the settings page itself where the user selects to use the sandpit - maybe something like a static form field with the hideif form setting that shows up a message in red when a user selects the sandpit option?

If you decide to just improve the string on the security page so that it flags a warning when sandbox is enabled I wouldn't block approval, but I think I'd prefer to see it on the settings page rather than a security check myself (or both locations if you really want it to be a security check) :-)
